### PR TITLE
Update graphics doc to describe clear, and remove code

### PR DESCRIPTION
**Pull request by iszla**
Removed the code at the end that is drawing a blank at the characters previous position since we are using clear() to blank the whole console.

### CODE REVIEW

**Comment by tomassedovic** [comment]
Good catch, thank you!

Before I merge this: the changes here will only show in the `src/bin/part-1b-movement.rs` section, any of the later ones still have the old `put_char(self.x, self.y, ' '...)` bit.

Would you mind updating all the other files? It will be confusing for people otherwise.

I understand it's annoying, so if you don't want to do it, I'll merge this and do it myself later (I just don't know when I'll be able to get to it).

**Comment by iszla** [comment]
No problem, I'll look at it after dinner. Great tutorial so far, I am just finishing up "The Dungeon" now

**Comment by tomassedovic** [comment]
Thank you for the kind words!

**Comment by iszla** [comment]
So the PR is quite a bit larger now :)
I had to rearrange the render_all function a bit, as we need to render the map on every frame. Even if the player has not moved since we clear the entire screen at the start of the loop.
Maybe this was the wrong way to go, but I feel like it worked out quite well.

**Comment by tomassedovic** [comment]
Thanks!

I've just tried this -- it builds fine and I like the code structure better -- but something is off. Running none of the examples seem to actually clear the previous position :-(.

You can try this by running `cargo run --bin part-13-adventure-gear` in the root of the repo.

I had a brief look at the code and I didn't see anything obviously wrong, but I'm minutes away from bedtime. I'll have another look sometime tomorrow.

I do like this removes one nesting level of that already complex function. Sorry this is turning out to be more work than what you bargained for!

**Comment by iszla** [comment]
I was just about to ask how I run each example, thanks! I found the issue, I was clearing the wrong console after the Offscreen one was added. So changing it to `con.clear()` instead of `root.clear()` solved it. I updated the relevant paragraph in the documentation/tutorial so the next person does not miss it as well haha
I tested 5-6 of the examples that had issues and they are working as expected now I think.

Nothing to worry about that it is more work, I am doing your tutorial because I wanted to learn rust. And I am learning it by doing this as well, mission accomplished!

**Comment by tomassedovic** [comment]
Wonderful, thank you!

**Pull request merged**
