### PR TITLE
Documentation grammar and spelling corrections

### PR DESCRIPTION
**Pull request by keisetsu**
I found a few grammatical and spelling changes as I was working through the tutorial, so I thought I'd offer them to you. I decided not to follow some of the later chapters because I felt like I was ready to start my own project, so I wasn't very thorough in chapters 12-13.

I made a couple of changes to code in the documentation as well; if you agree with those changes, the real code will need to be changed, too.

Thanks a lot for the tutorial, it really laid a great foundation both in using rust and in roguelike creation (this is my first attempt at a roguelike game)!

### CODE REVIEW

**Comment by tomassedovic** [comment]
This is excellent, thank you so much! I swear I know the difference between "it's" and "its" though :/.

Anyway, I'm happy to merge this as is but the as_mut issue was fixed in the meantime so this needs a rebase. I can do that myself later, but if you resubmit this I'll merge it asap.

No idea what happened with the irc html file -- that's from a completely different project.

**Comment by keisetsu** [comment]
I wouldn't worry too much about the it's/its business; I need someone else to check my usage too!
I'll work on rebasing, should have thought of that before I made the request.

**Comment by tomassedovic** [comment]
Thanks :-)

**Comment by keisetsu** [comment]
I'm closing this pull request: I ended up making an updated pull request from a branch (which I should have done in the first place), so it didn't automatically update this request.

**Pull request closed without merging**
